name: Weekly Build

on:
  workflow_dispatch:
  schedule:
    - cron: 0 12 * * 1

jobs:
  build:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y%m%d')"

      - name: Checkout branch "release"
        uses: actions/checkout@v3
        with:
          ref: 'release'
      - name: Download file
        env:
          GEOIP_CN_URL: ${{ secrets.GEOIP_CN_URL }}
          GEOIP_COUNTRY_URL: ${{ secrets.GEOIP_COUNTRY_URL }}
          GEOIP_CITY_URL: ${{ secrets.GEOIP_CITY_URL }}
        run: |
          wget -qO ./country_cn.mmdb "${GEOIP_CN_URL}"
          wget -qO ./country.mmdb "${GEOIP_COUNTRY_URL}"
          wget -qO ./city.mmdb "${GEOIP_CITY_URL}"
          
      - name: Git push
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Actio"
          git remote set-url origin https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git add .
          git commit --allow-empty -am "update"
          git push origin release
          git tag ${{ steps.date.outputs.date }}
          git push origin ${{ steps.date.outputs.date }}

      - name: Release
        uses: ncipollo/release-action@v1
        with:
            token: ${{ secrets.GITHUB_TOKEN }}
            artifacts: "./*.mmdb"
            tag: ${{ steps.date.outputs.date }}
            name: ${{ steps.date.outputs.date }}
            generateReleaseNotes: true
            body:  "订阅地址\n  country_cn.mmdb: https://raw.githubusercontent.com/caaby/geoip/release/country_cn.mmdb\n  country.mmdb: https://raw.githubusercontent.com/caaby/geoip/release/country.mmdb\n  city.mmdb: https://raw.githubusercontent.com/caaby/geoip/release/city.mmdb"
