name: Weekly Build

on:
  workflow_dispatch:
  schedule:
    - cron: 0 12 * * 1

jobs:
  build:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        id: date
        run: echo "today=$(date +'%Y%m%d')" >> $GITHUB_OUTPUT
        shell: bash

      - name: Checkout branch "release"
        uses: actions/checkout@v3
        with:
          ref: 'release'
      - name: Download file
        env:
          GEOIP_CN_URL: ${{ secrets.GEOIP_CN_URL }}
          GEOIP_COUNTRY_URL: ${{ secrets.GEOIP_COUNTRY_URL }}
          GEOIP_CITY_URL: ${{ secrets.GEOIP_CITY_URL }}
        run: |
          wget -qO ./country_cn.mmdb "${GEOIP_CN_URL}"
          wget -qO ./country.mmdb "${GEOIP_COUNTRY_URL}"
          wget -qO ./city.mmdb "${GEOIP_CITY_URL}"
          
      - name: Git push
        run: |
          git config --local user.email "fangling@outlook.com"
          git config --local user.name "caaby"
          git remote set-url origin https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git add .
          git commit --allow-empty -am "update"
          git push origin release
          git tag ${{ steps.date.outputs.today }}
          git push origin ${{ env.today }}

      - name: Release
        uses: ncipollo/release-action@v1
        with:
            token: ${{ secrets.GITHUB_TOKEN }}
            artifacts: "./*.mmdb"
            tag: ${{ steps.date.outputs.today }}
            name: ${{ steps.date.outputs.today }}
            generateReleaseNotes: true
