name: Weekly Build

on:
  workflow_dispatch:
  schedule:
    - cron: 0 12 * * 1

jobs:
  build:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y%m%d')"

      - name: Checkout branch "release"
        uses: actions/checkout@v3
        with:
          ref: 'release'
      - name: Download file
        env:
          GEOIP_URL: ${{ secrets.GEOIP_URL }}
        run: wget -qO ./Country_CN.mmdb "${GEOIP_URL}"
          
      - name: Git push
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Actio"
          git remote set-url origin https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git add .
          git commit --allow-empty -am "update"
          git push origin release
          git tag ${{ steps.date.outputs.date }}
          git push origin ${{ steps.date.outputs.date }}

      - name: Release
        uses: ncipollo/release-action@v1
        with:
            token: ${{ secrets.GITHUB_TOKEN }}
            artifacts: "Country_CN.mmdb"
            tag: ${{ steps.date.outputs.date }}
            name: ${{ steps.date.outputs.date }}
            generateReleaseNotes: true
            body: ${{ steps.date.outputs.date }}
