name: Weekly Build

on:
  workflow_dispatch:
  schedule:
  - cron: 0 12 * * 1

jobs:
  build:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Download file
        env:
          GEOIP_URL: ${{ secrets.GEOIP_URL }}
        run: |
            wget -qO ./Country_CN.mmdb "${GEOIP_URL}"

      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

      - name: Checkout branch "release"
        uses: actions/checkout@latest
        with:
          ref: 'release'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Actio"
          git remote set-url origin https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git commit --allow-empty -am "update"
          git push
          git tag ${{ steps.date.outputs.date }}
          git push origin ${{ steps.date.outputs.date }}

      - name: Release
        id: release-country
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.date.outputs.date }}
          release_name: ${{ steps.date.outputs.date }}
          draft: false
          prerelease: false
